/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.uniensinojavaswing.murilo.swing.jogo.da.velha.murilo.nata.nogueira.Visual;

import com.uniensinojavaswing.murilo.swing.jogo.da.velha.murilo.nata.nogueira.Controle.Controlador;
import java.awt.Dimension;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author muril
 */
public class TelaJogo extends javax.swing.JFrame {

    private boolean isPlayer1 = true;
    String[][] tabuleiro = {
        {"","",""},
        {"","",""},
        {"","",""}};
    private final Controlador controleJogo = new Controlador();
    private boolean fimJogo;
    private int jogadas = 0, pontosX = 0, pontosO = 0, empates = 0;
    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        preparaBotoes();
        textParabens1.setPreferredSize(new Dimension(textParabens1.getWidth(), textParabens1.getHeight()));
        textParabens1.setVisible(false);
        
        textParabens1.setPreferredSize(new Dimension(textParabens2.getWidth(), textParabens2.getHeight()));
        textParabens2.setVisible(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textPontosX = new javax.swing.JLabel();
        textPontosO = new javax.swing.JLabel();
        textEmpates = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        textIconeAtual = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        textParabens1 = new javax.swing.JLabel();
        BtnReiniciar = new javax.swing.JButton();
        textParabens2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(3, 3, 6, 6));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Pontos Jogador 2");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Empates");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Pontos Jogador 1");

        textPontosX.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textPontosX.setText("0");

        textPontosO.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textPontosO.setText("0");

        textEmpates.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        textEmpates.setText("0");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Status do Jogo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(textPontosX)
                            .addComponent(textPontosO)
                            .addComponent(textEmpates)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPontosX)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textPontosO)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textEmpates)
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("Jogador atual");

        textIconeAtual.setFont(new java.awt.Font("Segoe UI", 0, 72)); // NOI18N
        textIconeAtual.setText("X");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel4))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(textIconeAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(textIconeAtual)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setLayout(null);

        textParabens1.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        textParabens1.setText("Parabens Jogador 1 !!!");
        textParabens1.setDoubleBuffered(true);
        textParabens1.setFocusable(false);
        textParabens1.setInheritsPopupMenu(false);
        jPanel4.add(textParabens1);
        textParabens1.setBounds(0, 30, 260, 36);

        BtnReiniciar.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        BtnReiniciar.setText("REINICIAR");
        BtnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnReiniciarActionPerformed(evt);
            }
        });
        jPanel4.add(BtnReiniciar);
        BtnReiniciar.setBounds(290, 10, 280, 71);

        textParabens2.setFont(new java.awt.Font("Segoe UI", 0, 26)); // NOI18N
        textParabens2.setText("Parabens Jogador 2 !!!");
        jPanel4.add(textParabens2);
        textParabens2.setBounds(590, 30, 260, 36);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Ação geral para todos os botões que estão dentro do campo para o jogo da velha
    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
        JButton botao = (JButton) evt.getSource();
        final int linha = (int) botao.getClientProperty("linha");
        final int coluna = (int) botao.getClientProperty("coluna");
        if(botao.getText().isEmpty())
        {
            String suporte = isPlayer1 ? "X" : "O"; //Define o suporte que vai ajudar na pesquisa
            botao.setText(isPlayer1 ? "X" : "O"); //Coloca o texto referente ao jogador
            tabuleiro[linha][coluna] = isPlayer1 ? "X" : "O";
            jogadas++;
            fimJogo = controleJogo.verificaGanhador(tabuleiro, suporte);
            if(fimJogo)
            {
                logicaFinalJogo(false);
            } else if(isFull())
            {
                logicaFinalJogo(true);
            }
            
            
            isPlayer1 = !isPlayer1;
            textIconeAtual.setText(isPlayer1 ? "X" : "O");
            
        }
        
        //Desliga o botão
        botao.setEnabled(false);
    }//GEN-LAST:event_btnActionPerformed

    private void BtnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnReiniciarActionPerformed
        reativarBotoes();
        esvaziaMatriz();
        isPlayer1 = true;
        textIconeAtual.setText("X");
    }//GEN-LAST:event_BtnReiniciarActionPerformed

    private void logicaFinalJogo(boolean isEmpate){
        if(isEmpate)
        {
            JOptionPane.showMessageDialog(this, "Empate!");
            empates++;
        } else {
            JOptionPane.showMessageDialog(this, isPlayer1 ? "Jogador1 Ganhou" : "Jogador 2 Ganhou!");
            if(isPlayer1)
            {
                pontosX++;
                textParabens1.setVisible(true);
            } else {
                pontosO++;
                textParabens2.setVisible(true);
            }
        }
        
        desligarTodosBotoes();
        atualizarPontos();
    }
    
    private void desligarTodosBotoes(){
        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
        jButton8.setEnabled(false);
        jButton9.setEnabled(false);
    }
    
    private void atualizarPontos(){
        textPontosX.setText(Integer.toString(pontosX));
        textPontosO.setText(Integer.toString(pontosO));
        textEmpates.setText(Integer.toString(empates));
    }
    
    
    private void reativarBotoes(){
        jButton1.setEnabled(true);
        jButton1.setText("");
        
        jButton2.setEnabled(true);
        jButton2.setText("");
        
        jButton3.setEnabled(true);
        jButton3.setText("");
        
        jButton4.setEnabled(true);
        jButton4.setText("");
        
        jButton5.setEnabled(true);
        jButton5.setText("");
        
        jButton6.setEnabled(true);
        jButton6.setText("");
        
        jButton7.setEnabled(true);
        jButton7.setText("");
        
        jButton8.setEnabled(true);
        jButton8.setText("");
        
        jButton9.setEnabled(true);
        jButton9.setText("");
        
        textParabens1.setVisible(false);
        textParabens2.setVisible(false);
    }
    
    private void preparaBotoes(){
        jButton1.putClientProperty("linha", 0);
        jButton1.putClientProperty("coluna", 0);
        
        jButton2.putClientProperty("linha", 0);
        jButton2.putClientProperty("coluna", 1);
        
        jButton3.putClientProperty("linha", 0);
        jButton3.putClientProperty("coluna", 2);
        
        jButton4.putClientProperty("linha", 1);
        jButton4.putClientProperty("coluna", 0);
        
        jButton5.putClientProperty("linha", 1);
        jButton5.putClientProperty("coluna", 1);
        
        jButton6.putClientProperty("linha", 1);
        jButton6.putClientProperty("coluna", 2);
        
        jButton7.putClientProperty("linha", 2);
        jButton7.putClientProperty("coluna", 0);
        
        jButton8.putClientProperty("linha", 2);
        jButton8.putClientProperty("coluna", 1);
        
        jButton9.putClientProperty("linha", 2);
        jButton9.putClientProperty("coluna", 2);
        
    }
    
    private void esvaziaMatriz(){
        for(int i = 0; i < 3; i++)
        {
            for(int j = 0; j < 3; j++) {
                tabuleiro[i][j] = "";
            }
        }
    }
    
    private boolean isFull() {
        for(int i = 0; i < 3; i++)
        {
            for(int j = 0; j < 3; j++) {
                if(tabuleiro[i][j].equals(""))
                {
                    return false;
                }
            }
        }
        return true;
    }
    /**
     * 
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnReiniciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel textEmpates;
    private javax.swing.JLabel textIconeAtual;
    private javax.swing.JLabel textParabens1;
    private javax.swing.JLabel textParabens2;
    private javax.swing.JLabel textPontosO;
    private javax.swing.JLabel textPontosX;
    // End of variables declaration//GEN-END:variables
}
